In [1]:
import pandas as pd

In [2]:
movie_dataset = pd.read_csv(r"D:\my diractory\internship codespctra\dataset\movie recommentation dataset\tmdb_5000_movies.csv")
movie_dataset

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [4]:
movie_dataset.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [3]:
movie_dataset.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [5]:
movie_dataset.shape

(4803, 20)

In [6]:
movie_dataset.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [7]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
'''# Sample movie dataset
data = {'Title': ['Movie 1', 'Movie 2', 'Movie 3', 'Movie 4'],
        'Description': ['Action movie with car chases and explosions',
                         'Romantic comedy with love triangles',
                         'Sci-fi adventure with aliens and space exploration',
                         'Animated film with talking animals']}'''

"# Sample movie dataset\ndata = {'Title': ['Movie 1', 'Movie 2', 'Movie 3', 'Movie 4'],\n        'Description': ['Action movie with car chases and explosions',\n                         'Romantic comedy with love triangles',\n                         'Sci-fi adventure with aliens and space exploration',\n                         'Animated film with talking animals']}"

In [8]:
df = pd.DataFrame(movie_dataset)

In [9]:

# User's preferences
user_preferences = 'I love action movies with car chases and explosions'

In [13]:
# TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(movie_dataset['keywords'])

In [14]:
# TF-IDF Vectorizer for user preferences 
user_tfidf = tfidf_vectorizer.transform([user_preferences])

In [15]:
# Calculate cosine similarity
cosine_sim = linear_kernel(user_tfidf, tfidf_matrix)

In [22]:
# Get movie recommendations based on similarity
movie_indices = cosine_sim.argsort()[0][::-1]
recommended_movies = movie_dataset['original_title'].iloc[movie_indices]

In [32]:
print("User Preferences:", user_preferences)
print("Recommended Movies:")
print(recommended_movies)

User Preferences: In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.
Recommended Movies:
2050                 The Transporter Refueled
1937                            King's Ransom
405     The Fast and the Furious: Tokyo Drift
1521                         Cats Don't Dance
500                          2 Fast 2 Furious
                        ...
3141                              Next Friday
3140                            The Lost City
3138                                  Gunless
3137                                Nurse 3-D
2401                           City of Ghosts
Name: original_title, Length: 4803, dtype: object

In [31]:
user_preferences = 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [17]:
movie_dataset.dtypes

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
dtype: object

# K Nearest neighbor

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [8]:
# Sample data (replace this with your dataset)
X =  movie_dataset[['budget','genres','homepage','id','keywords','original_language','overview','popularity','production_companies','production_countries','release_date','revenue','runtime','spoken_languages','status','tagline','vote_average','vote_count']]
y = movie_dataset['title']

In [11]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [12]:
# Create a KNN classifier
knn = KNeighborsClassifier(n_neighbors=3)

In [13]:
# Train the classifier
knn.fit(X_train, y_train)

ValueError: could not convert string to float: '[{"id": 28, "name": "Action"}, {"id": 35, "name": "Comedy"}, {"id": 10402, "name": "Music"}, {"id": 10749, "name": "Romance"}, {"id": 37, "name": "Western"}]'

In [ ]:
# Make predictions on the test set
y_pred = knn.predict(X_test)

In [ ]:
# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

In [ ]:
import streamlit as st
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from streamlit_option_menu import option_menu
from streamlit_lottie import st_lottie
import json
import requests


data = pd.read_csv("C:\\Users\\Abinashkumar\\OneDrive\\Desktop\\New folder\\project_data-new 24-04-23.csv")
#data1 = pd.read_csv("C:\\Users\\mayur\\Downloads\\Variety.csv")
sns.set_style("darkgrid")
st.set_page_config(page_title= "Star Color Prediction", layout= "wide")

# Load the pre-trained machine learning model
model = joblib.load("abistar.joblib")

# Define the Streamlit app
def main():
    with st.sidebar:
        a = option_menu(
            menu_title ="Content",
            options = ["Home","Model","Visulization"],
            icons=["house","bar-chart-fill","envelope","heptagon-fill"],
            menu_icon="cast",
            default_index=0

        )
    #a = st.sidebar.selectbox("Content",("HomePage","Visulization","Model", "Variety"))

    if a == "Home":
        st.markdown("#  Star Color Prediction:")
        st.markdown("#####  It's an Star color Prediction app. We have real data about the star like Temperature, Luminosity, Radius, Absolute_Magnitude, Star_type, Spectral_class. we give thoese data then it will predict and Provided which more suitable for the give data it will show the Star color ")
        #st.image("agri2.jpg")
        def load_lottieurl(url: str):
            r = requests.get(url)
            if r.status_code != 200:
                return None
            return r.json()
        lottie_hello = load_lottieurl("https://assets6.lottiefiles.com/packages/lf20_0wpmp74s.json")
        st_lottie(
            lottie_hello,
            speed = 5,
            reverse= False,
            loop = True,
            height= 500,
            width = 800,
            quality= "high"

         )
        
            
        st.write("#### This app is a helpful tool for finding the star color.")
        #st.markdown(""" <style>.stApp{background: linear-gradient(to right, #36454F, #3DED97);} </style>""", unsafe_allow_html=True)
        #st.balloons()
    

        
    elif a == "Visulization":
        b = st.sidebar.selectbox("Graphs",("Boxen Plot", "Scatter Plot","Bar Plot"))
        

        if b == "Boxen Plot":

            st.markdown("<h1 style='text-align: center; color: green;'>Boxen Plot</h1>", unsafe_allow_html=True)
            Y = st.sidebar.selectbox("Y Axis", data.columns)
            fig = plt.figure(figsize=(12,6))
            sns.boxenplot(data = data,
                  x = data["Star type"],
                  y = data['Radius(R/Ro)'],
                  palette = "Blues")
            st.pyplot(fig)
        
        elif b == "Scatter Plot":
            st.markdown("<h1 style='text-align: center; color: green;'>Scatter Plot</h1>", unsafe_allow_html=True)
            Xy = st.sidebar.selectbox("X Axis", data.columns)
            y = st.sidebar.selectbox("Y Axis", data.columns)
            fig = plt.figure(figsize =(10,6))
            sns.scatterplot(data = data,
                            x = data['Radius(R/Ro)'],
                            y = data[y],
                            hue = "Temperature (K)"
                            )
            st.pyplot(fig)
        else :
            st.markdown("<h1 style='text-align: center; color: green;'>Bar Plot</h1>", unsafe_allow_html=True)
            y = st.sidebar.selectbox("Y Axis", data.columns)
            fig = plt.figure(figsize = (12,6))
            sns.barplot(data = data,
                        x = data["Temperature (K)"],
                        y = data[y],
                        )
            st.pyplot(fig)


    elif a == "Model":

        def predict():
            # Set the app title
            st.write("# :green[To Predict the star color using some star details]")
            st.write("#### Note: Collect the details Given in sidebar and fill it carefully",)
            st.write("### :blue[According to star detail output :]",prediction)
            st.write("###### Note :")
            st.write('###### :green[0 = The star color is RED]')
            st.write("###### :green[1 = The star color is BLUE WHITE]")
            st.write("###### :green[2 = The star color is YELLOW WHITE]")
            st.write("###### :green[3 = The star color is ORANGE]")
            st.write("###### :green[4 = The star color is YELLOW WISH]")
            st.write("###### :green[5 = The star color is PALE YELLOW ORANGE]")
            st.write("###### :green[6 = The star color is WHITE]")
            st.write("###### :green[7 = The star color is BLUE]")
            
        


        # Add user input for features
        temperature = st.sidebar.number_input("Temperature (1000 to 40000)")
        luminosity = st.sidebar.number_input("Luminosity (0 to 1)")
        Radius  = st.sidebar.number_input("Radius (0 to 1)")
        absolute_magnitude = st.sidebar.number_input("Absolute_Magnitude (0 to 20)")
        star_type = st.sidebar.number_input("Star_type (0 to 5)")
        Spectral_class = st.sidebar.number_input("Spectral_Class (0 to 7)")
       

    # Create a feature vector from user input
        features = [[temperature,luminosity,Radius,absolute_magnitude,star_type,Spectral_class]]

    # Predict the recommended crop
        prediction = model.predict(features)[0]
        if(prediction == 0):
           print('The star color is RED')
        elif(prediction == 1):
           print('The star color is BLUE WHITE ')
        elif(prediction == 2):
           print('The star color is YELLOW WHITE')
        elif(prediction == 3):
           print('The star color is ORANGE')
        elif(prediction == 4):
           print('The star color is YELLOW WISH')
        elif(prediction == 5):
           print('The star color is PALE YELLOW ORANGE')
        elif(prediction == 6):
           print('The star color is WHITE')
        else:
           print('The star color is BLUE')
        
        
        predict()

        
    

    # Display the recommended crop to the user
    

if _name_ == "_main_":
    main()